#!/bin/bash

# Variables -----------------------------------------------------------------------------#

blue='\033[0;36m'
green='\033[0;32m'
yellow='\033[1;33m'
red='\033[0;31m'
nocolor='\033[0m'

pcdata_location="/usr/bin/pcdata"
pcdata_manager_location="/usr/bin/pcdata-manager"

pcdata_url="https://raw.githubusercontent.com/JediFonseca/pcdata/refs/heads/main/pcdata"
pcdata_manager_url="https://raw.githubusercontent.com/JediFonseca/pcdata/refs/heads/main/pcdata-manager"

# Safety --------------------------------------------------------------------------------#

[[ $EUID -eq 0 ]] || {
    echo -e "${red}Error:${nocolor} this script must be run as root."
    exit 1
}

# Arrays --------------------------------------------------------------------------------#

declare -A debian_dependencies_list=(

["dmidecode"]="DMI Decode"
["util-linux"]="Util Linux"
["lm-sensors"]="LM Sensors"
["pciutils"]="PCI Utils"
["upower"]="UPower"
["x11-xserver-utils"]="xrandr"
["procps"]="Procps"
["iproute2"]="IP Route"
["usbutils"]="USB Utils"
["curl"]="curl"

)

declare -A arch_dependencies_list=(

[""]=""

)

declare -A fedora_dependencies_list=(

["dmidecode"]="DMI Decode"
["util-linux"]="Util Linux"
["lm_sensors"]="LM Sensors"
["pciutils"]="PCI Utils"
["upower"]="UPower"
["xrandr"]="xrandr"
["procps-ng"]="Procps NG"
["iproute"]="IP Route"
["usbutils"]="USB Utils"
["curl"]="curl"

)

# Function 01 ---------------------------------------------------------------------------#

which_distro () {

if command -v apt-get &> /dev/null; then

	echo -e "${blue}\nRunning on a Debian based distro...\n${nocolor}"
	distroid="debian"
	sleep 2

elif command -v pacman &> /dev/null; then

	echo -e "${blue}\nRunning on an Arch based distro...\n${nocolor}"
	distroid="arch"
	sleep 2

elif command -v dnf &> /dev/null; then

	echo -e "${blue}\nRunning on a Fedora based distro...\n${nocolor}"
	distroid="fedora"
	sleep 2

else

	echo -e "${red}\nError:${nocolor} this script is only compatible with Debian, Ubuntu, Arch and Fedora.\n"
	exit 1
  
fi

}

# Function 02 ---------------------------------------------------------------------------#

initial_message () {

local IFS=,

local apt="${debian_dependencies_list[*]}."
local pacman="${arch_dependencies_list[*]}."
local dnf="${fedora_dependencies_list[*]}."

clear

echo -e "${blue}-------------------- PCData Installation Script --------------------${nocolor}"
echo
echo -e "${yellow}When/if executed, this script will:${nocolor}"
echo
echo -e "${blue}1. Install the dependencies:${nocolor}"
[[ $distroid == "debian" ]] && echo "${apt//,/, }" | fold -s -w 90
[[ $distroid == "arch" ]] && echo "${pacman//,/, }" | fold -s -w 90
[[ $distroid == "fedora" ]] && echo "${dnf//,/, }" | fold -s -w 90
echo
echo -e "${blue}2. Download 'pcdata' and 'pcdata-manager' to '/usr/bin'.${nocolor}"
echo
echo -e "${blue}3. Give 'pcdata' and 'pcdata-manager' execution permissions with 'chmod +x'.${nocolor}"
echo
echo -e -n "${yellow}\nPress ENTER to install PCData or CTRL+C to cancel.${nocolor}"
read -r < /dev/tty
echo

}

# Function 03 ---------------------------------------------------------------------------#

dependencies_installation () {

if [[ $distroid == "debian" ]]; then

	echo -e "${yellow}Installing the dependencies with \"apt\".\n${nocolor}"
	echo
	apt update
	apt install -y "${!debian_dependencies_list[@]}"
		
fi

if [[ $distroid == "arch" ]]; then

	echo -e "${yellow}Installing the dependencies with \"pacman\".\n${nocolor}"
	echo
	pacman -Sy --noconfirm "${!arch_dependencies_list[@]}"
		
fi

if [[ $distroid == "fedora" ]]; then

	echo -e "${yellow}Installing the dependencies with \"dnf\".\n${nocolor}"
	echo
	dnf install -y "${!fedora_dependencies_list[@]}"
		
fi

}

# Function 04 ---------------------------------------------------------------------------#

download_scripts () {

wget --show-progress -O "$pcdata_location" "$pcdata_url" || { echo "pcdata download failed! Check your connection."; exit 1; }
wget --show-progress -O "$pcdata_manager_location" "$pcdata_manager_url" || { echo "pcdata-manager download failed! Check your connection."; exit 1; }

}

# Function 05 ---------------------------------------------------------------------------#

execution_permissions () {

chmod +x "$pcdata_location"
chmod +x "$pcdata_manager_location"

}

# Execution -----------------------------------------------------------------------------#

which_distro
initial_message
dependencies_installation
download_scripts
execution_permissions
echo
echo -e "${green}Script execution finished!${nocolor}"
