#!/bin/bash

#pcdata - Displays detailed hardware information, similar to CPU-Z
#Copyright (C) 2026 Jedielson da Fonseca

#This program is free software: you can redistribute it and/or modify
#it under the terms of the GNU General Public License version 3 as
#published by the Free Software Foundation.

#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.

#You should have received a copy of the GNU General Public License
#along with this program.  If not, see <https://www.gnu.org/licenses/>.

export LC_ALL=C

# Variables ----------------------------------------------------------------------#

green='\033[0;32m'
blue='\033[0;36m'
yellow='\033[1;33m'
red='\033[0;31m'
nocolor='\033[0m'

# Function 01 --------------------------------------------------------------------#

safety_checks () {

command -v dmidecode >/dev/null || {
    echo -e "${red}Erro:${nocolor} o pacote 'dmidecode' não está instalado."
    exit 1
}

command -v lscpu >/dev/null || {
    echo -e "${red}Erro:${nocolor} o pacote 'util-linux' não está instalado."
    exit 1
}

command -v sensors >/dev/null || {
    echo -e "${red}Erro:${nocolor} o pacote 'lm_sensors' não está instalado."
    exit 1
}

command -v lspci >/dev/null || {
    echo -e "${red}Erro:${nocolor} o pacote 'pciutils' não está instalado."
    exit 1
}

command -v upower >/dev/null || {
    echo -e "${red}Erro:${nocolor} o pacote 'upower' não está instalado."
    exit 1
}

command -v xrandr >/dev/null || {
    echo -e "${red}Erro:${nocolor} o pacote 'xrandr' não está instalado."
    exit 1
}

}

# Function 02 --------------------------------------------------------------------#

help_section () {

clear

    echo -e "${blue}How to use this script:${nocolor}\n"

    echo -e "Run \"pcdata\" for basic system and hardware information.\n"

    echo -e "${blue}For more details, use the following flags:${nocolor}"
    echo -e "--cpu: for advanced CPU information."
    echo -e "--ram: for advanced RAM information."

    echo -e "\n${blue}DEPENDENCIES:${nocolor}"
    echo -e "${blue}For this script to work properly, you'll need the following packages:${nocolor}"
    echo -e "dmidecode, lm_sensors, util-linux, xrandr, upower and pciutils. (Package names based on Fedora 44.)"
    echo "All of them are default on many distros, including Debian, but you may need to"
    echo "install some of them manually, specially in more minimalistic distros."

}

# Function 03 --------------------------------------------------------------------#

cpu_section () {

echo -e "${yellow}This script requires administrator privileges to read hardware data.${nocolor}"

        sudo -v || { echo -e "${red}Authentication failed!${nocolor}"; exit 1; }

        # Setting global variables.

        MANUFACTURER=$(sudo dmidecode -t processor | grep "Manufacturer" | sed 's/.*: *//')
        MODELNAME=$(grep -m1 "model name" /proc/cpuinfo | cut -d: -f2 | sed -e 's/^[ \t]*//')
        CORES=$(lscpu | grep "Core(s) per socket:" | awk '{print $4}')
        THREADS=$(lscpu | grep "^CPU(s):" | head -n1 | awk '{print $2}')
        GOVERNOR=$(cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor)
        SOCKET=$(sudo dmidecode -t processor | grep "Upgrade:" | cut -d: -f2 | sed -e 's/^[ \t]*//')
        VOLTAGE=$(sudo dmidecode -t processor | grep "Voltage" | sed 's/.*: *//')
        FAMILYNUMBER=$(grep -m1 "cpu family" /proc/cpuinfo | cut -d: -f2 | sed -e 's/^[ \t]*//')
        MODELNUMBER=$(grep "^model" /proc/cpuinfo | grep -v "model name" | head -n1 | cut -d: -f2 | sed 's/^[ \t]*//')
        STEPPING=$(grep -m1 "stepping" /proc/cpuinfo | cut -d: -f2 | sed -e 's/^[ \t]*//')
        INSTRUCTIONS=$(lscpu | grep -E "Flags|Options" \
            | grep -iowE "mmx|sse|sse2|sse3|ssse3|sse4_1|sse4_2|avx|avx2|avx512|fma|aes|sha|vmx|svm|lm" \
            | tr '[:lower:]' '[:upper:]' | tr '_' '.' | sort -u | xargs | sed 's/ /, /g')
        MAXCLOCK=$(sudo dmidecode -t processor | grep "Max Speed" | sed 's/.*: *//')
        CACHEL1D=$(lscpu | grep -E "L1d" | sed 's/.*: *//')
        CACHEL1I=$(lscpu | grep -E "L1i" | sed 's/.*: *//')
        CACHEL2=$(lscpu | grep -E "L2" | sed 's/.*: *//')
        CACHEL3=$(lscpu | grep -E "L3" | sed 's/.*: *//')

        # Formatting output and loop for the realtime information.

    while true; do

        # Variables for the realtime information.
        CPUTEMP=$(sensors | grep -E "Tctl:|Package id 0:" | awk '{print $4 ? $4 : $2}' \
            | tr -d '+') && CPUTEMP=${CPUTEMP:-"N/A (Install 'lm_sensors' and run the 'sensors-detect' command.)"}
        CLOCK=$(grep "cpu MHz" /proc/cpuinfo | head -n1 | cut -d: -f2 | sed -e 's/^[ \t]*//')
        MULTIPLIER=$(grep "cpu MHz" /proc/cpuinfo | head -n1 | cut -d: -f2 | awk '{printf "x%.1f\n", $1/100}')

        clear

        tput cup 0 0

        echo -e "${blue}------------------------ CPU INFORMATION ------------------------${nocolor}"

        echo -e "\n${blue}Static Information:${nocolor}"
        echo -e "Manufacturer:                 $MANUFACTURER"
        echo -e "Model Name:                   $MODELNAME"
        echo -e "Number of Cores:              $CORES"
        echo -e "Number of Threads:            $THREADS"
        echo -e "Governor (Power mode):        $GOVERNOR"
        echo -e "Socket:                       $SOCKET"
        echo -e "Default Voltage:              $VOLTAGE"
        echo -e "Family Number:                $FAMILYNUMBER"
        echo -e "Model Number:                 $MODELNUMBER"
        echo -e "Stepping:                     $STEPPING"
        echo -e "Maximum Clock Speed:          $MAXCLOCK"
        echo -e "Cache L1d:                    $CACHEL1D"
        echo -e "Cache L1i:                    $CACHEL1I"
        echo -e "Cache L2:                     $CACHEL2"
        echo -e "Cache L3:                     $CACHEL3"
        echo -e "Instructions:"
        echo -e "$INSTRUCTIONS" | fmt -w 75

        echo -e "\n${blue}Realtime information:${nocolor}"
        echo -e "Current Temperature:          $CPUTEMP"
        echo -e "Current Clock Speed:          $CLOCK"
        echo -e "Current Multiplier:           $MULTIPLIER"

        echo -e "\n${yellow}Press CTRL+C to exit.${nocolor}"

    sleep 1
    done

}

# Function 04 --------------------------------------------------------------------#

ram_section () {

echo -e "${yellow}This script requires administrator privileges to read hardware data.${nocolor}"

        sudo -v || { echo -e "${red}Authentication failed!${nocolor}"; exit 1; }

        # Defining variables.

        MEMCMD=$(sudo dmidecode -t 17)

        # RAM size per slot, from 1 to 6:
        MEMSIZE01=$(echo "$MEMCMD" | awk 'BEGIN{RS="Memory Device"} NR==2 {print}' | grep -w "Size:" \
            | grep -vE "Unknown|No Module Installed" | head -n1 | awk '{$1=""; print $0}' | sed 's/^[ \t]*//')
        MEMSIZE02=$(echo "$MEMCMD" | awk 'BEGIN{RS="Memory Device"} NR==3 {print}' | grep -w "Size:" \
            | grep -vE "Unknown|No Module Installed" | head -n1 | awk '{$1=""; print $0}' | sed 's/^[ \t]*//')
        MEMSIZE03=$(echo "$MEMCMD" | awk 'BEGIN{RS="Memory Device"} NR==4 {print}' | grep -w "Size:" \
            | grep -vE "Unknown|No Module Installed" | head -n1 | awk '{$1=""; print $0}' | sed 's/^[ \t]*//')
        MEMSIZE04=$(echo "$MEMCMD" | awk 'BEGIN{RS="Memory Device"} NR==5 {print}' | grep -w "Size:" \
            | grep -vE "Unknown|No Module Installed" | head -n1 | awk '{$1=""; print $0}' | sed 's/^[ \t]*//')
        MEMSIZE05=$(echo "$MEMCMD" | awk 'BEGIN{RS="Memory Device"} NR==6 {print}' | grep -w "Size:" \
            | grep -vE "Unknown|No Module Installed" | head -n1 | awk '{$1=""; print $0}' | sed 's/^[ \t]*//')
        MEMSIZE06=$(echo "$MEMCMD" | awk 'BEGIN{RS="Memory Device"} NR==7 {print}' | grep -w "Size:" \
            | grep -vE "Unknown|No Module Installed" | head -n1 | awk '{$1=""; print $0}' | sed 's/^[ \t]*//')

        # Memory type per slot, from 1 to 6:
        MEMTYPE01=$(echo "$MEMCMD" | awk 'BEGIN{RS="Memory Device"} NR==2 {print}' | grep -w "Type:" \
            | grep -vE "Unknown|No Module Installed" | head -n1 | awk '{$1=""; print $0}' | sed 's/^[ \t]*//')
        MEMTYPE02=$(echo "$MEMCMD" | awk 'BEGIN{RS="Memory Device"} NR==3 {print}' | grep -w "Type:" \
            | grep -vE "Unknown|No Module Installed" | head -n1 | awk '{$1=""; print $0}' | sed 's/^[ \t]*//')
        MEMTYPE03=$(echo "$MEMCMD" | awk 'BEGIN{RS="Memory Device"} NR==4 {print}' | grep -w "Type:" \
            | grep -vE "Unknown|No Module Installed" | head -n1 | awk '{$1=""; print $0}' | sed 's/^[ \t]*//')
        MEMTYPE04=$(echo "$MEMCMD" | awk 'BEGIN{RS="Memory Device"} NR==5 {print}' | grep -w "Type:" \
            | grep -vE "Unknown|No Module Installed" | head -n1 | awk '{$1=""; print $0}' | sed 's/^[ \t]*//')
        MEMTYPE05=$(echo "$MEMCMD" | awk 'BEGIN{RS="Memory Device"} NR==6 {print}' | grep -w "Type:" \
            | grep -vE "Unknown|No Module Installed" | head -n1 | awk '{$1=""; print $0}' | sed 's/^[ \t]*//')
        MEMTYPE06=$(echo "$MEMCMD" | awk 'BEGIN{RS="Memory Device"} NR==7 {print}' | grep -w "Type:" \
            | grep -vE "Unknown|No Module Installed" | head -n1 | awk '{$1=""; print $0}' | sed 's/^[ \t]*//')

        # Memory speed per slot, from 1 to 6:
        MEMSPEED01=$(echo "$MEMCMD" | awk 'BEGIN{RS="Memory Device"} NR==2 {print}' \
            | grep -w "Speed:" | grep -vE "Unknown|No Module Installed" | head -n1 | awk '{$1=""; print $0}' | sed 's/^[ \t]*//')
        MEMSPEED02=$(echo "$MEMCMD" | awk 'BEGIN{RS="Memory Device"} NR==3 {print}' \
            | grep -w "Speed:" | grep -vE "Unknown|No Module Installed" | head -n1 | awk '{$1=""; print $0}' | sed 's/^[ \t]*//')
        MEMSPEED03=$(echo "$MEMCMD" | awk 'BEGIN{RS="Memory Device"} NR==4 {print}' \
            | grep -w "Speed:" | grep -vE "Unknown|No Module Installed" | head -n1 | awk '{$1=""; print $0}' | sed 's/^[ \t]*//')
        MEMSPEED04=$(echo "$MEMCMD" | awk 'BEGIN{RS="Memory Device"} NR==5 {print}' \
            | grep -w "Speed:" | grep -vE "Unknown|No Module Installed" | head -n1 | awk '{$1=""; print $0}' | sed 's/^[ \t]*//')
        MEMSPEED05=$(echo "$MEMCMD" | awk 'BEGIN{RS="Memory Device"} NR==6 {print}' \
            | grep -w "Speed:" | grep -vE "Unknown|No Module Installed" | head -n1 | awk '{$1=""; print $0}' | sed 's/^[ \t]*//')
        MEMSPEED06=$(echo "$MEMCMD" | awk 'BEGIN{RS="Memory Device"} NR==7 {print}' | grep -w "Speed:" \
            | grep -vE "Unknown|No Module Installed" | head -n1 | awk '{$1=""; print $0}' | sed 's/^[ \t]*//')

        # Memory default voltage per slot, from 1 to 6:
        MEMVOLTAGE01=$(echo "$MEMCMD" | awk 'BEGIN{RS="Memory Device"} NR==2 {print}' \
            | grep "Configured Voltage:" | grep -vE "Unknown|No Module Installed" \
            | head -n1 | awk '{$1=""; $2=""; print $0}' | sed 's/^[ \t]*//')
        MEMVOLTAGE02=$(echo "$MEMCMD" | awk 'BEGIN{RS="Memory Device"} NR==3 {print}' \
            | grep "Configured Voltage:" | grep -vE "Unknown|No Module Installed" \
            | head -n1 | awk '{$1=""; $2=""; print $0}' | sed 's/^[ \t]*//')
        MEMVOLTAGE03=$(echo "$MEMCMD" | awk 'BEGIN{RS="Memory Device"} NR==4 {print}' \
            | grep "Configured Voltage:" | grep -vE "Unknown|No Module Installed" \
            | head -n1 | awk '{$1=""; $2=""; print $0}' | sed 's/^[ \t]*//')
        MEMVOLTAGE04=$(echo "$MEMCMD" | awk 'BEGIN{RS="Memory Device"} NR==5 {print}' \
            | grep "Configured Voltage:" | grep -vE "Unknown|No Module Installed" \
            | head -n1 | awk '{$1=""; $2=""; print $0}' | sed 's/^[ \t]*//')
        MEMVOLTAGE05=$(echo "$MEMCMD" | awk 'BEGIN{RS="Memory Device"} NR==6 {print}' \
            | grep "Configured Voltage:" | grep -vE "Unknown|No Module Installed" \
            | head -n1 | awk '{$1=""; $2=""; print $0}' | sed 's/^[ \t]*//')
        MEMVOLTAGE06=$(echo "$MEMCMD" | awk 'BEGIN{RS="Memory Device"} NR==7 {print}' \
            | grep "Configured Voltage:" | grep -vE "Unknown|No Module Installed" \
            | head -n1 | awk '{$1=""; $2=""; print $0}' | sed 's/^[ \t]*//')

        # Memory serial number per slot, from 1 to 6:
        MEMSN01=$(echo "$MEMCMD" | awk 'BEGIN{RS="Memory Device"} NR==2 {print}' \
            | grep "Serial Number:" | grep -vE "Unknown|No Module Installed" \
            | head -n1 | awk '{$1=""; $2=""; print $0}' | sed 's/^[ \t]*//')
        MEMSN02=$(echo "$MEMCMD" | awk 'BEGIN{RS="Memory Device"} NR==3 {print}' \
            | grep "Serial Number:" | grep -vE "Unknown|No Module Installed" \
            | head -n1 | awk '{$1=""; $2=""; print $0}' | sed 's/^[ \t]*//')
        MEMSN03=$(echo "$MEMCMD" | awk 'BEGIN{RS="Memory Device"} NR==4 {print}' \
            | grep "Serial Number:" | grep -vE "Unknown|No Module Installed" \
            | head -n1 | awk '{$1=""; $2=""; print $0}' | sed 's/^[ \t]*//')
        MEMSN04=$(echo "$MEMCMD" | awk 'BEGIN{RS="Memory Device"} NR==5 {print}' \
            | grep "Serial Number:" | grep -vE "Unknown|No Module Installed" \
            | head -n1 | awk '{$1=""; $2=""; print $0}' | sed 's/^[ \t]*//')
        MEMSN05=$(echo "$MEMCMD" | awk 'BEGIN{RS="Memory Device"} NR==6 {print}' \
            | grep "Serial Number:" | grep -vE "Unknown|No Module Installed" \
            | head -n1 | awk '{$1=""; $2=""; print $0}' | sed 's/^[ \t]*//')
        MEMSN06=$(echo "$MEMCMD" | awk 'BEGIN{RS="Memory Device"} NR==7 {print}' \
            | grep "Serial Number:" | grep -vE "Unknown|No Module Installed" \
            | head -n1 | awk '{$1=""; $2=""; print $0}' | sed 's/^[ \t]*//')

        # Memory part number per slot, from 1 to 6:
        MEMPN01=$(echo "$MEMCMD" | awk 'BEGIN{RS="Memory Device"} NR==2 {print}' \
            | grep "Part Number:" | grep -vE "Unknown|No Module Installed" \
            | head -n1 | awk '{$1=""; $2=""; print $0}' | sed 's/^[ \t]*//')
        MEMPN02=$(echo "$MEMCMD" | awk 'BEGIN{RS="Memory Device"} NR==3 {print}' \
            | grep "Part Number:" | grep -vE "Unknown|No Module Installed" \
            | head -n1 | awk '{$1=""; $2=""; print $0}' | sed 's/^[ \t]*//')
        MEMPN03=$(echo "$MEMCMD" | awk 'BEGIN{RS="Memory Device"} NR==4 {print}' \
            | grep "Part Number:" | grep -vE "Unknown|No Module Installed" \
            | head -n1 | awk '{$1=""; $2=""; print $0}' | sed 's/^[ \t]*//')
        MEMPN04=$(echo "$MEMCMD" | awk 'BEGIN{RS="Memory Device"} NR==5 {print}' \
            | grep "Part Number:" | grep -vE "Unknown|No Module Installed" \
            | head -n1 | awk '{$1=""; $2=""; print $0}' | sed 's/^[ \t]*//')
        MEMPN05=$(echo "$MEMCMD" | awk 'BEGIN{RS="Memory Device"} NR==6 {print}' \
            | grep "Part Number:" | grep -vE "Unknown|No Module Installed" \
            | head -n1 | awk '{$1=""; $2=""; print $0}' | sed 's/^[ \t]*//')
        MEMPN06=$(echo "$MEMCMD" | awk 'BEGIN{RS="Memory Device"} NR==7 {print}' \
            | grep "Part Number:" | grep -vE "Unknown|No Module Installed" \
            | head -n1 | awk '{$1=""; $2=""; print $0}' | sed 's/^[ \t]*//')

        # Memory Form Factor per slot, from 1 to 6:
        MEMFF01=$(echo "$MEMCMD" | awk 'BEGIN{RS="Memory Device"} NR==2 {print}' \
            | grep "Form Factor:" | grep -v "Unknown" | awk '{print $3}')
        MEMFF02=$(echo "$MEMCMD" | awk 'BEGIN{RS="Memory Device"} NR==3 {print}' \
            | grep "Form Factor:" | grep -v "Unknown" | awk '{print $3}')
        MEMFF03=$(echo "$MEMCMD" | awk 'BEGIN{RS="Memory Device"} NR==4 {print}' \
            | grep "Form Factor:" | grep -v "Unknown" | awk '{print $3}')
        MEMFF04=$(echo "$MEMCMD" | awk 'BEGIN{RS="Memory Device"} NR==5 {print}' \
            | grep "Form Factor:" | grep -v "Unknown" | awk '{print $3}')
        MEMFF05=$(echo "$MEMCMD" | awk 'BEGIN{RS="Memory Device"} NR==6 {print}' \
            | grep "Form Factor:" | grep -v "Unknown" | awk '{print $3}')
        MEMFF06=$(echo "$MEMCMD" | awk 'BEGIN{RS="Memory Device"} NR==7 {print}' \
            | grep "Form Factor:" | grep -v "Unknown" | awk '{print $3}')

        # Formatting output

        clear

        echo -e "${blue}------------------------ RAM INFORMATION ------------------------${nocolor}"

        echo -e "\n${blue}Memory size per slot:${nocolor}"
        [[ -n "$MEMSIZE01" ]] && echo -e "Slot 01: $MEMSIZE01${nocolor}"
        [[ -n "$MEMSIZE02" ]] && echo -e "Slot 02: $MEMSIZE02${nocolor}"
        [[ -n "$MEMSIZE03" ]] && echo -e "Slot 03: $MEMSIZE03${nocolor}"
        [[ -n "$MEMSIZE04" ]] && echo -e "Slot 04: $MEMSIZE04${nocolor}"
        [[ -n "$MEMSIZE05" ]] && echo -e "Slot 05: $MEMSIZE05${nocolor}"
        [[ -n "$MEMSIZE06" ]] && echo -e "Slot 06: $MEMSIZE06${nocolor}"

        echo -e "\n${blue}Memory type per slot:${nocolor}"
        [[ -n "$MEMTYPE01" ]] && echo -e "Slot 01: $MEMTYPE01${nocolor}"
        [[ -n "$MEMTYPE02" ]] && echo -e "Slot 02: $MEMTYPE02${nocolor}"
        [[ -n "$MEMTYPE03" ]] && echo -e "Slot 03: $MEMTYPE03${nocolor}"
        [[ -n "$MEMTYPE04" ]] && echo -e "Slot 04: $MEMTYPE04${nocolor}"
        [[ -n "$MEMTYPE05" ]] && echo -e "Slot 05: $MEMTYPE05${nocolor}"
        [[ -n "$MEMTYPE06" ]] && echo -e "Slot 06: $MEMTYPE06${nocolor}"

        echo -e "\n${blue}Memory speed per slot:${nocolor}"
        [[ -n "$MEMSPEED01" ]] && echo -e "Slot 01: $MEMSPEED01${nocolor}"
        [[ -n "$MEMSPEED02" ]] && echo -e "Slot 02: $MEMSPEED02${nocolor}"
        [[ -n "$MEMSPEED03" ]] && echo -e "Slot 03: $MEMSPEED03${nocolor}"
        [[ -n "$MEMSPEED04" ]] && echo -e "Slot 04: $MEMSPEED04${nocolor}"
        [[ -n "$MEMSPEED05" ]] && echo -e "Slot 05: $MEMSPEED05${nocolor}"
        [[ -n "$MEMSPEED06" ]] && echo -e "Slot 06: $MEMSPEED06${nocolor}"

        echo -e "\n${blue}Memory Form Factor per slot:${nocolor}"
        [[ -n "$MEMFF01" ]] && echo -e "Slot 01: $MEMFF01${nocolor}"
        [[ -n "$MEMFF02" ]] && echo -e "Slot 02: $MEMFF02${nocolor}"
        [[ -n "$MEMFF03" ]] && echo -e "Slot 03: $MEMFF03${nocolor}"
        [[ -n "$MEMFF04" ]] && echo -e "Slot 04: $MEMFF04${nocolor}"
        [[ -n "$MEMFF05" ]] && echo -e "Slot 05: $MEMFF05${nocolor}"
        [[ -n "$MEMFF06" ]] && echo -e "Slot 06: $MEMFF06${nocolor}"

        echo -e "\n${blue}Memory default voltage per slot:${nocolor}"
        [[ -n "$MEMVOLTAGE01" ]] && echo -e "Slot 01: $MEMVOLTAGE01${nocolor}"
        [[ -n "$MEMVOLTAGE02" ]] && echo -e "Slot 02: $MEMVOLTAGE02${nocolor}"
        [[ -n "$MEMVOLTAGE03" ]] && echo -e "Slot 03: $MEMVOLTAGE03${nocolor}"
        [[ -n "$MEMVOLTAGE04" ]] && echo -e "Slot 04: $MEMVOLTAGE04${nocolor}"
        [[ -n "$MEMVOLTAGE05" ]] && echo -e "Slot 05: $MEMVOLTAGE05${nocolor}"
        [[ -n "$MEMVOLTAGE06" ]] && echo -e "Slot 06: $MEMVOLTAGE06${nocolor}"

        echo -e "\n${blue}Memory serial number per slot:${nocolor}"
        [[ -n "$MEMSN01" ]] && echo -e "Slot 01: $MEMSN01${nocolor}"
        [[ -n "$MEMSN02" ]] && echo -e "Slot 02: $MEMSN02${nocolor}"
        [[ -n "$MEMSN03" ]] && echo -e "Slot 03: $MEMSN03${nocolor}"
        [[ -n "$MEMSN04" ]] && echo -e "Slot 04: $MEMSN04${nocolor}"
        [[ -n "$MEMSN05" ]] && echo -e "Slot 05: $MEMSN05${nocolor}"
        [[ -n "$MEMSN06" ]] && echo -e "Slot 06: $MEMSN06${nocolor}"

        echo -e "\n${blue}Memory part number per slot:${nocolor}"
        [[ -n "$MEMPN01" ]] && echo -e "Slot 01: $MEMPN01${nocolor}"
        [[ -n "$MEMPN02" ]] && echo -e "Slot 02: $MEMPN02${nocolor}"
        [[ -n "$MEMPN03" ]] && echo -e "Slot 03: $MEMPN03${nocolor}"
        [[ -n "$MEMPN04" ]] && echo -e "Slot 04: $MEMPN04${nocolor}"
        [[ -n "$MEMPN05" ]] && echo -e "Slot 05: $MEMPN05${nocolor}"
        [[ -n "$MEMPN06" ]] && echo -e "Slot 06: $MEMPN06${nocolor}"

}

# Function 05 --------------------------------------------------------------------#

main_section () {

# Defining variables:

        OSNAME=$(grep -E '^PRETTY_NAME=' /etc/os-release | cut -d= -f2 | tr -d '"')
        DENAME=$(echo $XDG_CURRENT_DESKTOP)
        KERNELNAME=$(uname -r)
        UPTIME=$(uptime -p | sed 's/up //')
        SHELLNAME=$(echo "${SHELL##*/} $( $SHELL --version | grep -oE '[0-9]+\.[0-9.]+' | head -n1 )")
        CPUNAME=$(grep -m1 "model name" /proc/cpuinfo | cut -d: -f2 | sed -e 's/^[ \t]*//')
        GPUNAME=$(lspci | grep -iE 'vga|3d|display' | sed -E 's/.*\[(.*)\].*/\1/' | xargs | sed 's/ /, /g')
        TOTALRAM=$(free -k | grep "Mem:" | awk '{printf "%.1f GiB\n", $2/1024/1024}')
        TOTALSWAP=$(free -h | awk '/^Swap:/ {print $2}')
        MYDISKS=$(df -h --output=source,used,size,pcent,target,fstype | grep "^/dev/" \
            | sed 's/  */,/g; s/,fuseblk/,ntfs/g; s/,ntfs3/,ntfs/g' \
            | awk -v color="$blue" -v nc="$nocolor" -F, \
            '{printf "%sDisk (%s):%s %s / %s (%s) em %s [%s]\n", color, $1, nc, $2, $3, $4, $5, $6}')
        MYMONITORS=$(xrandr --query 2>/dev/null | awk -v color="$blue" -v \
            nc="$nocolor" '/ connected/ {p=$1} /\*/ {res=$1; freq=$2; gsub(/[*+]/, "", \
            freq); printf "%s%s:%s %s @ %sHz\n", color, p, nc, res, freq}')
        MYIP=$(ip -br addr show | grep UP | awk '{print $3}' | cut -d/ -f1)
        VIDEODRIVER=$(lspci -k | grep -EiA 3 "vga|video|3d" | grep "in use" | sed 's/.*: //')
        IFBAT=$(upower -i $(upower -e 2>/dev/null | grep 'BAT') 2>/dev/null | grep 'percentage' | awk '{print $2}')

        # Formatting output

        clear

        echo -e "${blue}------------------ GENERAL SYSTEM INFORMATION ------------------${nocolor}\n"

        echo -e "${blue}OS:${nocolor} $OSNAME"
        echo -e "${blue}DE:${nocolor} $DENAME"
        echo -e "${blue}Kernel:${nocolor} $KERNELNAME"
        echo -e "${blue}Uptime:${nocolor} $UPTIME"
        echo -e "${blue}Shell:${nocolor} $SHELLNAME"
        echo -e "${blue}CPU:${nocolor} $CPUNAME"
        echo -e "${blue}Total RAM:${nocolor} $TOTALRAM"
        echo -e "${blue}Total swap:${nocolor} $TOTALSWAP"
        echo -e "${blue}GPU:${nocolor} $GPUNAME"
        echo -e "${blue}Video driver in use:${nocolor} $VIDEODRIVER"
        echo -e "$MYMONITORS"
        echo -e "${blue}Local IP:${nocolor} $MYIP"
        [[ -n "$IFBAT" ]] && echo -e "${blue}Battery percentage:${nocolor} $IFBAT"
        echo -e "$MYDISKS"


        echo -e "\n${yellow}Run \"pcdata --help\" for dependencies and more information on how to use it.${nocolor}"

}

# Execution ----------------------------------------------------------------------#

safety_checks

case "$1" in
    "--help")

    		help_section

    ;;

    "--cpu")

        cpu_section
        
    ;;

    "--ram")

        ram_section
        
    ;;

    *)
        
        main_section
        
    ;;
esac
