#!/bin/bash

# Check if is sudo. If not, reruns itself with sudo.
if [[ $EUID -ne 0 ]]; then
    exec sudo "$0" "$@"
fi

session="PCData"

# Check if session already exists.
if tmux has-session -t "$session" 2> /dev/null; then
    tmux attach -t "$session"
    exit 0
fi

# Creates session and tabs.
tmux new-session -d -s "$session" -n "MAIN" "pcdata-main; while true; do sleep 3600; done"
tmux new-window -t "$session" -n "CPU" "pcdata-main --cpu"
tmux new-window -t "$session" -n "RAM" "pcdata-main --ram"
tmux new-window -t "$session" -n "GPU" "pcdata-main --gpu"
tmux new-window -t "$session" -n "NOW" "pcdata-main --now"
tmux new-window -t "$session" -n "HELP" "pcdata-main --help; while true; do sleep 3600; done"
tmux new-window -t "$session" -n "UPDATE" "read -n1 -s -r -p 'Press any key to update PCData...'; echo; pcdata-main --update; while true; do sleep 3600; done"
tmux new-window -t "$session" -n "UNINSTALL" "read -n1 -s -r -p 'Press any key to uninstall PCData...'; echo; pcdata-main --uninstall; tmux kill-session -t $session"
tmux new-window -t "$session" -n "EXIT" "read -n1 -s -r -p 'Press any key to exit PCData...'; tmux kill-session -t $session"

# Activates mouse interaction and set the tabs bar to the top.
tmux set -g mouse on
tmux set -g status-position top

# Set the custom config file location.
config_file="/usr/share/pcdata.tmux.conf"
[[ -f "$config_file" ]] && tmux source-file "$config_file"

# Select the default tab and brings tmux to the first plan.
tmux select-window -t "$session:MAIN"
tmux attach -t "$session"
