#!/bin/bash

#pcdata - Displays detailed hardware information, similar to CPU-Z
#Copyright (C) 2026 Jedielson da Fonseca
#Contact: jedifn7@gmail.com

#This program is free software: you can redistribute it and/or modify
#it under the terms of the GNU General Public License version 3 as
#published by the Free Software Foundation.

#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.

#You should have received a copy of the GNU General Public License
#along with this program.  If not, see <https://www.gnu.org/licenses/>.

green='\033[0;32m'
yellow='\033[1;33m'
nocolor='\033[0m'

pcdata_url="https://raw.githubusercontent.com/JediFonseca/pcdata/refs/heads/main/pcdata"
pcdata_path="/usr/bin/pcdata"
manager_path="/usr/bin/pcdata-manager"

pcdata_update () {

echo -e "${yellow}\nDownloading and installing the new PCData version...${nocolor}"
wget -q -O "$pcdata_path" "$pcdata_url" || { echo "Update failed! Check your connection."; exit 1; }
chmod +x "$pcdata_path"
echo -e "${green}\nPCData is updated!\n${nocolor}"

}

pcdata_uninstall () {

echo -e "${yellow}\nUninstalling PCData...${nocolor}"
rm -f "$pcdata_path" &> /dev/null
rm -f "$manager_path" &> /dev/null
echo -e "${green}\nPCData is uninstalled!\n${nocolor}"

}

case "$1" in
    "--uninstall")	pcdata_uninstall		;;
    "--update")		pcdata_update		;;
esac
